blog_macka/account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name='accounts'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('register/', views.register, name='register'),
    # path('password_reset',
         # auth_views.PasswordResetView.as_view(),
         # name='password_reset'),
    path('', include('django.contrib.auth.urls')),
]

blog_macka/blog/urls.py
from django.urls import path
from . import views
from .views import PostEntry

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('create_post/', views.create_post, name='create_post'),
    path('create_pic/', views.create_pic, name='create_pic'),
    path('pic_list/', views.pic_list, name='pic_list'),
    # path('<int:pk>-<str:slug>/', views.post_entry, name='post_entry'),
    path('<int:pk>-<str:slug>/', PostEntry.as_view(), name='post_entry'),
]

blog_macka/blog_macka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog_macka/account/models.py
from django.db import models

# Create your models here.

blog_macka/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.conf import settings


# Create your models here.
class Picture(models.Model):
    title = models.CharField(max_length=250)
    author = models.CharField(max_length=150, blank=True)
    pic = models.ImageField(upload_to='imgs/')

    def __str__(self):
        return self.pic.url


class BlogEntry(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(default='',
                            editable=False,
                            max_length=250)
    author = models.ForeignKey('auth.User',
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    pictures = models.ManyToManyField(Picture)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        kwargs = {
            'pk': self.id,
            'slug': self.slug
        }
        return reverse('blog:post_entry', kwargs=kwargs)

    @property
    def main_picture(self):
        if self.pictures.exists():
            return self.pictures.all()[0]

blog_macka/account/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(label='Nazwa użytkownika')
    password = forms.CharField(widget=forms.PasswordInput, label="Hasło")


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='hasło',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='powtórz hasło',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Hasła nie pokrywają się!')
        return cd['password2']

blog_macka/blog/forms.py
from django import forms
from .models import BlogEntry, Picture


class CreateNewPost(forms.ModelForm):
    pictures = forms.ModelMultipleChoiceField(queryset=Picture.objects.all(), label="Wybierz zdjęcia")
    title = forms.CharField(max_length=150, label="Tytuł wpisu")
    body = forms.CharField(label="Treść wpisu")

    class Meta:
        model = BlogEntry
        fields = (
            'title',
            'body',
            'pictures',
        )
#     'pictures',

class PhotoAddForm(forms.ModelForm):
    # entry = forms.ModelChoiceField(
    #     queryset=BlogEntry.objects.all(),
    #     widget=forms.HiddenInput(),
    # )

    class Meta:
        model = Picture
        fields = ('title', 'author', 'pic')

blog_macka/account/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm

# Create your views here.


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'account/register_done.html',
                          {"new_user": new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html',
                  {"user_form": user_form})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                login(request, user)
                return render(request, 'account/login_success.html',
                              {'form': form})
            else:
                return HttpResponse('Konto nieaktywne!')
        else:
            return HttpResponse("Złe dane logowania")
    else:
        form = LoginForm()
        return render(request, 'account/login.html',
                      {'form': form})

blog_macka/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.utils.text import slugify
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from .models import BlogEntry, Picture
from .forms import CreateNewPost, PhotoAddForm

# Create your views here.


def post_list(request):
    posts = BlogEntry.objects.all()
    return render(request,
                  'blog/list.html',
                  {'posts': posts})


class PostEntry(DetailView):
    model = BlogEntry
    query_pk_and_slug = True
    template_name = 'blog/entry.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['main_picture'] = ctx.get('object').pictures.all()[0]
        ctx['other_pix'] = ctx.get('object').pictures.all()[1:]
        return ctx

# def post_entry(request, post):
#     post = get_object_or_404(BlogEntry)
#     return render(request,
#                   'blog/entry.html',
#                   {'post': post})


def pic_list(request):
    pictures = Picture.objects.all()
    return render(request,
                  'blog/pic_list.html',
                  {'pictures': pictures})


@login_required
def create_post(request):
    if request.method == 'POST':
        form = CreateNewPost(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.publish = timezone.now()
            value = post.title
            post.slug = slugify(value, allow_unicode=False)
            post.save()
            form.save_m2m()
            return redirect('blog:post_entry', pk=post.pk, slug=post.slug)
    else:
        form = CreateNewPost()
    return render(request, 'blog/create_post.html',
                  {'form': form,
                   })


@login_required
def create_pic(request):
    if request.method == 'POST':
        form = PhotoAddForm(data=request.POST,
                            files=request.FILES)
        if form.is_valid():
            form.save()
            return render(request, 'blog/create_pic.html',
                          {'form': form,
                           })
    else:
        form = PhotoAddForm()
    return render(request,
                  'blog/create_pic.html',
                  {'form': form,
                   })

blog_macka/account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}Blog Maćka{% endblock %}</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'css/base.css' %}" rel='stylesheet'>
    <link href="{% static 'css/base.css' %}" rel='stylesheet'>
  </head>
  <body>
    <div id="header">
      <span class="logo"><a href="{% url 'blog:post_list' %}">Blog Maćka</a></span>
      <a href="{% url 'blog:pic_list' %}">Galeria fot!</a>
      <span class="user">
        {% if request.user.is_authenticated %}
          Cześć, {{ request.user.first_name }}! |
          <a href="{% url 'blog:create_post' %}">Dodaj wpis</a> |
          <a href="{% url 'blog:create_pic' %}">Dodaj fotkę</a> |
          <a href="{% url 'account:logout' %}">Wyloguj</a>
        {% else %}
          <a href="{% url 'account:login' %}">Logowanie</a>
        {% endif %}
      </span>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

blog_macka/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}Blog Maćka{% endblock %}</title>

  </head>
  <body>
    <div id="header">
      <span class="logo"><a href="{% url 'post_list' %}">Blog Maćka</a></span>
      <a href="{% url 'pic_list' %}">Galeria fot!</a>
      <span class="user">
        {% if request.user.is_authenticated %}
          Cześć, {{ request.user.first_name }}! |
          <a href="{% url 'create_post' %}">Dodaj wpis</a> |
          <a href="{% url 'create_pic' %}">Dodaj fotkę</a>
          <a href="{% url 'logout' %}">Wyloguj</a>
        {% else %}
          <a href="{% url 'login' %}">Logowanie</a>
        {% endif %}
      </span>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

blog_macka/blog/templates/blog/create_pic.html
{% extends 'base.html' %}

{% block title %}Dodaj zdjęcie{% endblock %}

{% block content %}
  <h1>Dodaj fotkę do zbioru fotek</h1>
  <p>Korzystając z poniższego formularza, wyślij foktę do bazy danych:</p>
  <form method="post" class="form-group" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Dodaj obrazek" class="btn btn-success"></p>
  </form>
{% endblock %}

blog_macka/blog/templates/blog/create_post.html
{% extends 'base.html' %}

{% block title %}Dodaj wpis{% endblock %}

{% block content %}
  <h1>Dodaj nowy wpis do Twojego bloga!</h1>
    <form method="post" class="form-group">
        {% csrf_token %}
        <select name="obrazki" multiple>
            {% for picture in form.fields.pictures.choices %}
                    <div style="width: 600px; height: 700px">
                        <option value="{{ picture.0 }}" style="background-image: url({{ picture.1 }});
                                width: 600px;
                                height: 278px;"><br/>
                        </option>
                    </div>
            {% endfor %}
        </select>
        <p><input type="submit" value="Dodaj wpis" class="btn btn-success"></p>
    </form>
{% endblock %}

blog_macka/blog/templates/blog/entry.html
{% extends 'base.html' %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
  <h1>{{ object.title }}</h1>
  {{ object.publish }} : {{ object.author.first_name }}
  <br />
  {{ object.body }}
    <div>
    MAIN PICTURE <img src="{{ main_picture.pic.url }}" alt="{{ main_picture.title }}" width=640 height=480>
        {% for pictur in other_pix %}
            <h2>{{ pictur.title }}</h2><br />
            <img src = "{{ pictur.pic.url }}" width=640 height=480/>
        {% empty %}
            <p>GOWNO</p>
        {% endfor %}
    </div>
{% endblock %}

blog_macka/blog/templates/blog/list.html
{% extends 'base.html' %}

{% block title %}Pierwszy blog Maćka{% endblock %}

{% block content %}
  <h1>Wpisy na temat różynch rzeczy</h1>
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </h2>
    <p class="date">{{ post.author.first_name }} : {{ post.created }}</p>
    {{ post.body|truncatewords:30|linebreaks }}
    {%  if post.main_picture %}
        <img src="{{ post.main_picture.pic.url }}"/>
    {% endif %}
  {% empty %}
  <h2>Na razie nic nie mam do powiedzenia :( </h2>
  {% endfor %}
{% endblock %}